config/routes.rb
Rails.application.routes.draw do
  namespace :igdb do
    resources :games
    resources :themes
    resources :platforms
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/igdb/game.rb
class Igdb::Game < IgdbRecord
end

app/models/igdb/platform.rb
class Igdb::Platform < IgdbRecord
end

app/models/igdb/theme.rb
class Igdb::Theme < IgdbRecord
end

app/models/igdb_record.rb
class IgdbRecord < ApplicationRecord
  self.abstract_class = true
  self.table_name_prefix = 'igdb_'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/igdb/games_controller.rb
module Igdb
  # RESTful controller to manage game resources
  class GamesController < ApplicationController
    before_action :set_igdb_game, { only: %i[show edit update destroy] }

    # GET /igdb/games
    # GET /igdb/games.json
    def index
      @igdb_games = Igdb::Game.page(params[:page])
    end

    # GET /igdb/games/1
    # GET /igdb/games/1.json
    def show; end

    # GET /igdb/games/new
    def new
      @igdb_game = Igdb::Game.new
    end

    # GET /igdb/games/1/edit
    def edit; end

    # POST /igdb/games
    # POST /igdb/games.json
    def create
      @igdb_game = Igdb::Game.new(igdb_game_params)

      respond_to do |format|
        if @igdb_game.save
          format.html { redirect_to @igdb_game, { notice: 'Game was successfully created.' } }
          format.json { render :show, { status: :created, location: @igdb_game } }
        else
          format.html { render :new }
          format.json { render({ json: @igdb_game.errors, status: :unprocessable_entity }) }
        end
      end
    end

    # PATCH/PUT /igdb/games/1
    # PATCH/PUT /igdb/games/1.json
    def update
      respond_to do |format|
        if @igdb_game.update(igdb_game_params)
          format.html { redirect_to @igdb_game, { notice: 'Game was successfully updated.' } }
          format.json { render :show, { status: :ok, location: @igdb_game } }
        else
          format.html { render :edit }
          format.json { render({ json: @igdb_game.errors, status: :unprocessable_entity }) }
        end
      end
    end

    # DELETE /igdb/games/1
    # DELETE /igdb/games/1.json
    def destroy
      @igdb_game.destroy
      respond_to do |format|
        format.html { redirect_to igdb_games_url, { notice: 'Game was successfully destroyed.' } }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_igdb_game
      @igdb_game = Igdb::Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def igdb_game_params
      params.require(:igdb_game).permit(:igdb, :name, :slug)
    end
  end
end

app/controllers/igdb/platforms_controller.rb
class Igdb::PlatformsController < ApplicationController
  before_action :set_igdb_platform, only: [:show, :edit, :update, :destroy]

  # GET /igdb/platforms
  # GET /igdb/platforms.json
  def index
    @igdb_platforms = Igdb::Platform.all
  end

  # GET /igdb/platforms/1
  # GET /igdb/platforms/1.json
  def show
  end

  # GET /igdb/platforms/new
  def new
    @igdb_platform = Igdb::Platform.new
  end

  # GET /igdb/platforms/1/edit
  def edit
  end

  # POST /igdb/platforms
  # POST /igdb/platforms.json
  def create
    @igdb_platform = Igdb::Platform.new(igdb_platform_params)

    respond_to do |format|
      if @igdb_platform.save
        format.html { redirect_to @igdb_platform, notice: 'Platform was successfully created.' }
        format.json { render :show, status: :created, location: @igdb_platform }
      else
        format.html { render :new }
        format.json { render json: @igdb_platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /igdb/platforms/1
  # PATCH/PUT /igdb/platforms/1.json
  def update
    respond_to do |format|
      if @igdb_platform.update(igdb_platform_params)
        format.html { redirect_to @igdb_platform, notice: 'Platform was successfully updated.' }
        format.json { render :show, status: :ok, location: @igdb_platform }
      else
        format.html { render :edit }
        format.json { render json: @igdb_platform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /igdb/platforms/1
  # DELETE /igdb/platforms/1.json
  def destroy
    @igdb_platform.destroy
    respond_to do |format|
      format.html { redirect_to igdb_platforms_url, notice: 'Platform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_igdb_platform
      @igdb_platform = Igdb::Platform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def igdb_platform_params
      params.require(:igdb_platform).permit(:igdb, :name, :slug)
    end
end

app/controllers/igdb/themes_controller.rb
class Igdb::ThemesController < ApplicationController
  before_action :set_igdb_theme, only: [:show, :edit, :update, :destroy]

  # GET /igdb/themes
  # GET /igdb/themes.json
  def index
    @igdb_themes = Igdb::Theme.all
  end

  # GET /igdb/themes/1
  # GET /igdb/themes/1.json
  def show
  end

  # GET /igdb/themes/new
  def new
    @igdb_theme = Igdb::Theme.new
  end

  # GET /igdb/themes/1/edit
  def edit
  end

  # POST /igdb/themes
  # POST /igdb/themes.json
  def create
    @igdb_theme = Igdb::Theme.new(igdb_theme_params)

    respond_to do |format|
      if @igdb_theme.save
        format.html { redirect_to @igdb_theme, notice: 'Theme was successfully created.' }
        format.json { render :show, status: :created, location: @igdb_theme }
      else
        format.html { render :new }
        format.json { render json: @igdb_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /igdb/themes/1
  # PATCH/PUT /igdb/themes/1.json
  def update
    respond_to do |format|
      if @igdb_theme.update(igdb_theme_params)
        format.html { redirect_to @igdb_theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @igdb_theme }
      else
        format.html { render :edit }
        format.json { render json: @igdb_theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /igdb/themes/1
  # DELETE /igdb/themes/1.json
  def destroy
    @igdb_theme.destroy
    respond_to do |format|
      format.html { redirect_to igdb_themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_igdb_theme
      @igdb_theme = Igdb::Theme.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def igdb_theme_params
      params.require(:igdb_theme).permit(:igdb, :name, :slug)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/igdb/games_helper.rb
module Igdb::GamesHelper
end

app/helpers/igdb/platforms_helper.rb
module Igdb::PlatformsHelper
end

app/helpers/igdb/themes_helper.rb
module Igdb::ThemesHelper
end

app/views/igdb/games/_form.html.erb
<%= form_with(model: igdb_game, local: true) do |form| %>
  <% if igdb_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(igdb_game.errors.count, "error") %> prohibited this igdb_game from being saved:</h2>

      <ul>
      <% igdb_game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :igdb %>
    <%= form.number_field :igdb %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/igdb/games/edit.html.erb
<h1>Editing Igdb Game</h1>

<%= render 'form', igdb_game: @igdb_game %>

<%= link_to 'Show', @igdb_game %> |
<%= link_to 'Back', igdb_games_path %>

app/views/igdb/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Igdb Games</h1>

<table>
  <thead>
    <tr>
      <th>Igdb</th>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @igdb_games.each do |igdb_game| %>
      <tr>
        <td><%= igdb_game.igdb %></td>
        <td><%= igdb_game.name %></td>
        <td><%= igdb_game.slug %></td>
        <td><%= link_to 'Show', igdb_game %></td>
        <td><%= link_to 'Edit', edit_igdb_game_path(igdb_game) %></td>
        <td><%= link_to 'Destroy', igdb_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Igdb Game', new_igdb_game_path %>

<%= paginate @igdb_games %>

app/views/igdb/games/new.html.erb
<h1>New Igdb Game</h1>

<%= render 'form', igdb_game: @igdb_game %>

<%= link_to 'Back', igdb_games_path %>

app/views/igdb/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Igdb:</strong>
  <%= @igdb_game.igdb %>
</p>

<p>
  <strong>Name:</strong>
  <%= @igdb_game.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @igdb_game.slug %>
</p>

<%= link_to 'Edit', edit_igdb_game_path(@igdb_game) %> |
<%= link_to 'Back', igdb_games_path %>

app/views/igdb/platforms/_form.html.erb
<%= form_with(model: igdb_platform, local: true) do |form| %>
  <% if igdb_platform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(igdb_platform.errors.count, "error") %> prohibited this igdb_platform from being saved:</h2>

      <ul>
      <% igdb_platform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :igdb %>
    <%= form.number_field :igdb %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/igdb/platforms/edit.html.erb
<h1>Editing Igdb Platform</h1>

<%= render 'form', igdb_platform: @igdb_platform %>

<%= link_to 'Show', @igdb_platform %> |
<%= link_to 'Back', igdb_platforms_path %>

app/views/igdb/platforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Igdb Platforms</h1>

<table>
  <thead>
    <tr>
      <th>Igdb</th>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @igdb_platforms.each do |igdb_platform| %>
      <tr>
        <td><%= igdb_platform.igdb %></td>
        <td><%= igdb_platform.name %></td>
        <td><%= igdb_platform.slug %></td>
        <td><%= link_to 'Show', igdb_platform %></td>
        <td><%= link_to 'Edit', edit_igdb_platform_path(igdb_platform) %></td>
        <td><%= link_to 'Destroy', igdb_platform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Igdb Platform', new_igdb_platform_path %>

app/views/igdb/platforms/new.html.erb
<h1>New Igdb Platform</h1>

<%= render 'form', igdb_platform: @igdb_platform %>

<%= link_to 'Back', igdb_platforms_path %>

app/views/igdb/platforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Igdb:</strong>
  <%= @igdb_platform.igdb %>
</p>

<p>
  <strong>Name:</strong>
  <%= @igdb_platform.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @igdb_platform.slug %>
</p>

<%= link_to 'Edit', edit_igdb_platform_path(@igdb_platform) %> |
<%= link_to 'Back', igdb_platforms_path %>

app/views/igdb/themes/_form.html.erb
<%= form_with(model: igdb_theme, local: true) do |form| %>
  <% if igdb_theme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(igdb_theme.errors.count, "error") %> prohibited this igdb_theme from being saved:</h2>

      <ul>
      <% igdb_theme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :igdb %>
    <%= form.number_field :igdb %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/igdb/themes/edit.html.erb
<h1>Editing Igdb Theme</h1>

<%= render 'form', igdb_theme: @igdb_theme %>

<%= link_to 'Show', @igdb_theme %> |
<%= link_to 'Back', igdb_themes_path %>

app/views/igdb/themes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Igdb Themes</h1>

<table>
  <thead>
    <tr>
      <th>Igdb</th>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @igdb_themes.each do |igdb_theme| %>
      <tr>
        <td><%= igdb_theme.igdb %></td>
        <td><%= igdb_theme.name %></td>
        <td><%= igdb_theme.slug %></td>
        <td><%= link_to 'Show', igdb_theme %></td>
        <td><%= link_to 'Edit', edit_igdb_theme_path(igdb_theme) %></td>
        <td><%= link_to 'Destroy', igdb_theme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Igdb Theme', new_igdb_theme_path %>

app/views/igdb/themes/new.html.erb
<h1>New Igdb Theme</h1>

<%= render 'form', igdb_theme: @igdb_theme %>

<%= link_to 'Back', igdb_themes_path %>

app/views/igdb/themes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Igdb:</strong>
  <%= @igdb_theme.igdb %>
</p>

<p>
  <strong>Name:</strong>
  <%= @igdb_theme.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @igdb_theme.slug %>
</p>

<%= link_to 'Edit', edit_igdb_theme_path(@igdb_theme) %> |
<%= link_to 'Back', igdb_themes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GqrimbIgdb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>